# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AEAE
version:      0.02
version_from: lib/AEAE.pm
installdirs:  site
requires:
    CGI:                           3.15
    CGI::Ajax:                     0.683
    Class::AutoAccess:             0.02
    Data::UUID:                    0.11
    POSIX:                         1.05
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
